#!/usr/bin/env bash
#
# Archive a single file/directory.
#

archive_dir="$HOME/archive"

if [[ $# != 1 ]]; then
    echo "error: expected 1 argument (got $#)"
    exit 1
fi

if [[ ! -e "$1" ]]; then
    echo "error: file/directory specified does not exist ($1)"
    exit 2
fi

file_to_archive="$1"
archive="$archive_dir/$(date +%Y-%m-%d)-${file_to_archive##*/}.tar.xz"

if [[ -e "$archive" ]]; then
    echo "error: output archive file already exists ($archive)"
    exit 3
fi

XZ_OPT=-9 tar -Jcvpf "$archive" "$file_to_archive"

if [[ $? == 0 ]]; then
    echo "Archived $file_to_archive to $archive"
else
    echo "error: something went wrong while tarring"
    exit 4
fi
