#!/usr/bin/env bash
#
# Take a screenshot of an area and save it in a specific directory with a
# templated name.
#

shot_dir="$HOME/school/report/img/test"
shot_name="$(date +%F_%T)_cs-test-img.png"

scrot "$shot_dir/$shot_name"
test_id="$(zenity --entry \
       --title="${0##*/}" \
       --text="Test ID:")"
ln -s "$shot_name" "$shot_dir/
shot_symlink=
