#!/usr/bin/env bash
#
# Render a file by guessing its markup from the extension.
#

pre="render"

error() {
    echo "$1"
    exit 1
}

render_markdown() {
    markdown-render -o "$1"
}

render_tex() {
    tex-render "$1"
}

if [[ $# != 1 ]]; then
    error "should have exactly 1 argument (file to render)"
fi

file="$1"
ext="${file##*.}"

case "$ext" in
    md) ft="markdown" ;;
    tex) ft=$ext ;;
    *) ft="markdown" ;; # assume markdown if extension is not recognised
esac

render_$ft "$file"
