#!/usr/bin/env bash
#
# Reload a driver and restart a netctl profile.
#

driver="rtl8723be"
current_profile="$(netctl list | grep "^\*" | cut -d ' ' -f 2)"

sudo modprobe -r "$driver" && sudo modprobe "$driver" && sudo netctl restart "$current_profile"
