#!/usr/bin/env bash
#
# Write a short note.
#

regex_note_num="s/.*-note-([0-9]).md$/\1/p" 

journal_dir="$HOME/journal"



prev_num="$(ls "$journal_dir" | sed -En "$regex_note_num" | tail -n1)"
next_num=$(($prev_num + 1))

cd "$journal_dir"
new-from-template.py note "$next_num"
git add "$(date "+%F")-$(ezstring "Note $next_num").md"
git commit -m "add daily note #$next_num"
git push
