#!/usr/bin/env bash
#
# Run a command in a tmux session and exit when it finishes.
#
# Just a tiny bit easier than `tmux new "args"`.
#

# necessary to get all args in one string (for some reason, can't just
# quote $@
args="$@"

# start a new session and run a command, exiting on completion
tmux new-session "$args"
